### ISSUE TITLE
Exclude Excalidraw Paths

### ISSUE THREAD

**Issue by justanotherjurastudent** [mnaoumov/obsidian-better-markdown-links#9] opened 2024-09-15 10:19 UTC
Hi,
I'm encountering an issue where the embed links to an Excalidraw file are being converted and appended with an alias, which disrupts the intended size of the embed. The size is typically indicated by a "|", but when using an alias, the size cannot be applied.
I made a video of that problem:

https://github.com/user-attachments/assets/221353c6-fd8c-4e08-b72a-44bb70647db8

Can you add a rule, that files, which contains "Excalidraw" in the path, stay untouched from your plugin?
Thanks for reply in advance!

**Comment by mnaoumov** [comment] 2024-09-18 03:12
Cannot reproduce. Please retest with the latest version. If the issue persists, please attach a copy of the sample vault with the issue

**Comment by justanotherjurastudent** [comment] 2024-09-19 19:56
Hi,
Unfortunately, I simply cannot reproduce it in the sandbox vault. I have a normal Vault where the Excalidraw file is not embedded correctly if the note is in a 
folder. Only then does it not work. In the Sandbox Vault, where I have loaded exactly the same settings and plugins, it also works in folders as it should. I do not understand this. Maybe there was an earlier plugin in my Vault that did something wrong. I find that strange. In any case, I was able to identify the error for myself.
In the settings under File/Links, relative path is set and wikilinks are activated (I don't think markdown links are so good for internal links). I have activated the compatibility mode in the settings of your plugin. Here is a picture.
![image](https://github.com/user-attachments/assets/12437da0-de3e-4180-93a0-87975a7d7767)
The incorrect embedding only occurs when I embed it in a note within a folder. If I then delete the generated alias from your plugin in the wikilink or delete the prefix characters for the relative path (i.e. ../../), the Excalidraw file appears again as it should.
As I said, I only have these problems with Excalidraw files. Even if the error cannot be reproduced, it would be great if you could do something about it. Maybe add an option that the plugin should not add an alias automatically or something. If not, it's not too bad. This issue only concerns the case where I copy the embed link for a drawing and then paste it. If I embed the drawing via an Excalidraw command, everything is correct.

**Comment by mnaoumov** [comment] 2024-09-19 20:29
@justanotherjurastudent

1. I tried to reproduce the issue with `Excalidraw` plugin and I couldn't
2. The alias not meant to be added at all. This was a bug in the older version of the plugin.
3. As you set `Ignore incompatible Obsidian settings`, the plugin will create markdown links regardless of your setting `Use [[Wikilinks]]`
4. Your suggestion about the setting of not adding an alias might make sense but it should not be doing it for your case anyways.
5. As you cannot reproduce the issue on the Sandbox vault, how about you taking a full copy of your vault where it misbehaves, remove enough content to keep the issue reproducible and attach that copy here?

**Comment by justanotherjurastudent** [comment] 2024-09-20 07:17
@mnaoumov Hey, ok. I have 3 sketches in the excalidraw folder. Two of them won't work when I copy the embed link of them and paste it in a note within a folder. One sketch, which I created later, perhaps with other settings, work. I think, when you create a Excalidraw sketch and then for the first time copy the link to it, the link won't change later, even when you change link settings. That's why I think, the latest sketch work because of other link settings in the general Obsidian settings.
[test.zip](https://github.com/user-attachments/files/17071324/test.zip)

**Comment by mnaoumov** [comment] 2024-09-20 14:38
@justanotherjurastudent Thanks for your vault copy. I still cannot reproduce the issue. Please see the video attached.

https://github.com/user-attachments/assets/12a03c39-4cc7-447e-a231-c9d99e58eac3

**Comment by justanotherjurastudent** [comment] 2024-09-20 14:51
Yeah, this way is still working. 
My problem appeared when I opened the scratch, made a right click on the scratch space and then copied the embed link. Then I went to the notice in a folder and pastes the embed link. Then the link transformed through your PlugIn and the svg from the scratch doesn't appeared or is to small.

**Comment by mnaoumov** [comment] 2024-09-20 14:58
@justanotherjurastudent thanks, finally could reproduce the issue. Working on it

**Comment by mnaoumov** [comment] 2024-09-20 15:02
@justanotherjurastudent While I am fixing the unnecessary alias added, please note

```markdown
[[link|alias|size]]
```

also works

**Comment by justanotherjurastudent** [comment] 2024-09-20 16:04
> @justanotherjurastudent While I am fixing the unnecessary alias added, please note
> 
> ```
> ![[link|alias|size]]
> ```
> 
> also works

Ah ok, I never tried that. Thx!

**Comment by mnaoumov** [comment] 2024-09-20 16:29
Fixed in https://github.com/mnaoumov/obsidian-better-markdown-links/releases/tag/2.8.0

**Closed by mnaoumov** 2024-09-20 16:29 UTC
Labels: bug, question

**Comment by justanotherjurastudent** [comment] 2024-09-20 16:37
@mnaoumov Thank you!
